### ISSUE TITLE
Race when uploading files

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1213]
```
time="2020-07-22T09:00:00.502881100Z" level=warning msg="Failed to store metadata" func="storeFileAndMetadata\n\t" file=" [/build/dendrite-master/mediaapi/routing/upload.go:238]" MediaID=ZjRPeFpYX3hfRk81TGNHQlNLSFdYZnd0U3gtajFuY29TdDNTQUJKdGtHaw Origin=hs1 error="UNIQUE constraint failed: mediaapi_media_repository.media_id, mediaapi_media_repository.media_origin" req.id=oObZ2aQ5uAv7 req.method=POST req.path=/_matrix/media/r0/upload user_id="@alice:hs1"
time="2020-07-22T09:00:00.503122300Z" level=info msg="Responding (50 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=400 req.id=oObZ2aQ5uAv7 req.method=POST req.path=/_matrix/media/r0/upload
```
To repro: run complement test `TestMediaWithoutFileName` which does some media uploads/downloads in parallel.

**Comment by neilalexander** [comment]
The same file is being uploaded more than once?

**Comment by Kegsay** [comment]
Yes

**Comment by neilalexander** [comment]
The media repository table has a unique index on `media_id, media_origin`. Given that the `media_id` is a hash of the file then this will happen if the same file is uploaded more than once from the same place.

We might need to rethink how the media IDs are generated so that the hash also includes the `upload_name`, so that uploading the same file with different names will get unique media IDs correctly (so that we give the correct `Content-Disposition` name on download). Then we can store the media filename (based on the file hash only) as a separate column so that the actual file can still be deduplicated.

**Comment by turt2live** [comment]
Using the hash for the media ID is going to be more problematic as time goes on, even when including the (optional) file name. Largely for legal purposes, users cannot remove content for other users even if the content is the same - assigning a unique media ID to each upload gets around this so that when user A asks for their stuff to be deleted then user B's content remains (even if exactly the same hash).

**Comment by turt2live** [comment]
It would also cause problems for redactions: mxc uris are *generally* assumed to be linked to one or few events, rather than a piece of media. There's no hard relationship on this, but when servers are required to delete media because it has been redacted it will need to know which media ID to purge, which could break things for bystanders.

**Comment by Kegsay** [comment]
I want to land complement into CI so this needs to be fixed before I can do that and hard-fail tests based on it.
