### ISSUE TITLE
Implement registration with a shared secret

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1299]
Sytests:
```
    × POST /r0/admin/register with shared secret
    × POST /r0/admin/register admin with shared secret
    × POST /r0/admin/register with shared secret downcases capitals
    × POST /r0/admin/register with shared secret disallows symbols
```

**Comment by alam0rt** [comment]
I'm going to give this a go

**Comment by alam0rt** [comment]
Hey, pretty new to Go/the codebase...

In https://github.com/matrix-org/sytest/blob/develop/tests/10apidoc/01register.pl#L290 I can see that sytest is hitting
`/_synapse/admin/v1/register` whereas the test output in your comment shows `/r0/admin/register` as the path.

Are you able to point me in the right direction?

I am currently looking at https://github.com/matrix-org/dendrite/blob/f0a088b487df860d51c4e534bd59c330076d0cff/clientapi/routing/routing.go and was thinking of implementing the missing features similar to https://github.com/matrix-org/dendrite/blob/35ea55e70bf9d4e9db8fe0e0c741f685dcedf0ec/clientapi/routing/admin_whois.go

Thanks :)

**Comment by perj** [comment]
I think the sytest output above is from the sytest master branch, if that helps.

**Comment by tulir** [comment]
@alam0rt the `/_matrix/client/r0/admin` paths are deprecated, `/_synapse/admin/v1` is the correct place for synapse-compatible shared secret registration.

Also note that there is already [dendrite-specific shared secret registration](https://github.com/matrix-org/dendrite/blob/v0.3.3/clientapi/routing/register.go#L600-L612) implemented way back in #257 (which is probably not used for anything, because it's dendrite-specific)

**Comment by perj** [comment]
Ah, ok, so this registration method is not anything communicated to the client.
Rather it is meant to be used by batch scripts etc.
Now this makes much more sense...

**Comment by alam0rt** [comment]
Cheers. Thanks for clarifying

**Comment by piyushsingariya** [comment]
@jaywink @perj @Kegsay Is this issue still open or it is fixed?
