### ISSUE TITLE
Implement searching through the public room lists

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1302]
Spec: https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-publicrooms
Sytests:
```
    × Can search public room list
```

**Comment by bronger** [comment]
Since this was closed a long time ago, I am confused … I see the very same search results list in Element’s “explore rooms” feature no matter which search string I enter.  The search results depend on the server I choose but on nothing else.  The nginx logs

    10.32.0.32 - - [20/Dec/2021:20:53:03 +0000] "OPTIONS /_matrix/client/r0/publicRooms?server=matrix.org HTTP/2.0" 200 0 "-" …

while I do the search. Can this trouble be related to Dendrite? And if so, should this issue be re-opened?

Tested with commit a47b12dc.
