### ISSUE TITLE
Fix issues around /roomId/messages

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1309]
Sytests:
```
    × Local room members can get room messages
    × Remote room members can get room messages
    × Can get rooms/{roomId}/messages for a departed room (SPEC-216)
```

**Comment by alexkursell** [comment]
I looked into these two tests:

```
 × Local room members can get room messages
 × Remote room members can get room messages
```

They are failing because they expect the message events to contain a `user_id` field, which synapse does but which is not in the spec. I have no idea why synapse includes it either. It's always a copy of the `sender` field.

I guess the options here are either to modify the tests to check for `sender` instead, add the redundant field to dendrite or just ignore those tests.

**Comment by torabshaikh** [comment]
Hi @Kegsay I want to start contributing to the project and this looks like a good issue to start that. Can you please guide me on this?

**Comment by MadLittleMods** [comment]
@alexkursell I think it would be best to edit the test.

The `user_id` is part of the v1 old style of events. Currently, Synapse emits v1 properties merged into the v2 spec for compatibility but there are plans to remove them soon™, https://github.com/matrix-org/synapse/issues/6452

`sender` is the property to use instead.

Also discussed at https://gitlab.com/gitterHQ/webapp/-/merge_requests/2040#note_438956625 which is how I am aware.

**Comment by Kegsay** [comment]
Fab, thanks for looking into this @alexkursell - I've made a PR on Sytest to fix this and a few other places where we were doing the same thing.

@torabshaikh - it looks like this issue was with the tests and not Dendrite, so I've resolved this upstream.
