### ISSUE TITLE
Fix joining a room twice

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1311]
Sytests:
```
    × Joining room twice is idempotent
```

**Comment by Tert0** [comment]
I get ```
Test 138 Joining room twice is idempotent... EXPECTED FAIL
```as output for SyTests.

Does that mean that it works?

**Comment by kegsay** [comment]
No, it should be `... OK`

**Comment by nicobao** [comment]
Hi,
I am looking at it.

**Comment by kegsay** [comment]
Still failing as of today.

**Comment by nicobao** [comment]
> Still failing as of today.

 II had started and struggled at logging the relevant logs from the Perl fixture. I tried to figure out what part of the Go code was called.
Then, for some reason I thought I received a notification that someone had fixed it that's why I didn't update my previous post. My apologies for misleading you that I would fix the issue. Unfortunately, I won't have time to go further for a while, I am overwhelmed with work. So if anyone wants, please do go ahead and fix this issue.

**Comment by S7evinK** [comment]
Fixed in https://github.com/matrix-org/dendrite/pull/2512 or rather in https://github.com/matrix-org/sytest/pull/1256
