### ISSUE TITLE
syncapi: failed to map all event IDs to events

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/dendrite#1564]
### Background information

- **Dendrite version or git SHA**: 0.2.1 (with some additions; my open PRs)
- **Monolith or Polylith?**: polylith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: yes
- **`go version`**: 1.15

### Description

After joining `#archlinux:archlinux.org` (quite large, with 4.5k users and 450+ servers) i received the following error in the `syncapi`:
```
time="2020-10-24T18:21:53.710378246Z" level=error msg="rp.currentSyncForUser failed" func="github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).OnIncomingSyncRequest" file="github.com/matrix-org/dendrite/syncapi/sync/requestpool.go:82" device_id=qji0jlMp error="rp.db.IncrementalSync: d.addPDUDeltaToResponse: failed to map all event IDs to events: (got 6013, wanted 6014)" limit=20 req.id=X44ObqralQmc req.method=GET req.path=/_matrix/client/r0/sync since=s3040_4070.dl-0-0 timeout=0s user_id="@s7evink:dendrite.s3cr3t.me"
```
After closing my Element Web tab for about an hour, this seems to have resolved itself.

Before that, the `roomserver` added 6018 states.
```
time="2020-10-24T18:18:58.626414872Z" level=info msg="Producing to topic 'DendriteOutputRoomEvent'" func="github.com/matrix-org/dendrite/roomserver/internal/input.(*Inputer).WriteOutputEvents" file="github.com/matrix-org/dendrite/roomserver/internal/input/input.go:98" adds_state=6018 event_id="$-U5gTmET1qRcusr99n3pgSCERQEjo-LE4py6nEn8QfA" event_type=m.room.member removes_state=0 room_id="!SEgsRQLScqPxYtucHl:archlinux.org" send_as_server="" sender="@s7evink:dendrite.s3cr3t.me" type=new_room_event
```

### Steps to reproduce

- Sucessfully join `#archlinux:archlinux.org`, after several failed attempts

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
[syncapi.log](https://github.com/matrix-org/dendrite/files/5434655/syncapi.log)
[roomserver.log](https://github.com/matrix-org/dendrite/files/5434656/roomserver.log)

**Comment by ArnoPoitt** [comment]
### Background information

- **Dendrite version** 0.3.2
- **Monolith or Polylith**?: monolith
- **SQlite3 or Postgres** ?: Postgres
- **Running in docker** ? : Yes
- **Go version** : Not able to find go related files in the container

### Description

I have a very similar issue, although it is not the same line of the requestpool file sending an error.
It happened quit suddently, I was invited to join a room and also added new users who I invited at the same time.

`level=error msg="rp.currentSyncForUser failed" func="OnIncomingSyncRequest\n\t" file=" [github.com/matrix-org/dendrite/syncapi/sync/requestpool.go:132]" device_id=x1UKnMmk error="rp.db.IncrementalSync: d.addPDUDeltaToResponse: failed to map all event IDs to events: (got 37, wanted 38)" limit=20 req.id=iUWuiatAmyfH req.method=GET req.path=/_matrix/client/r0/sync since=s29131_37363.dl-0-0 timeout=0s user_id="@name:server.tld"`

### Steps to reproduce 

I don't really know honestly
I miss configured the container so I am not able to find the logs which journalctl

**Comment by neilalexander** [comment]
There's a temporary mitigation in commit bad81c028f090af0e1005076829db67d1a749a14 for this, but I'm going to leave the issue open for now because it's not permanently resolved.

**Comment by kegsay** [comment]
Feels like a similar issue to https://github.com/matrix-org/dendrite/issues/1544 - we need to be able to more gracefully handle missing events e.g by fetching them

**Comment by S7evinK** [comment]
Didn't see this for a long time, so closing this.
