### ISSUE TITLE
Dendrite is memory hungry using GBs of RAM

### ISSUE THREAD

**Issue by z3ntu** [matrix-org/dendrite#1580]
### Background information

- **Dendrite version or git SHA**: 0.2.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**: No
- **`go version`**: 1.15.3

### Description

Dendrite uses quite a lot of memory on my test server having joined ~10 medium traffic rooms.

![image](https://user-images.githubusercontent.com/3768500/99087566-36a05c80-25cb-11eb-996b-afcc0e77b923.png)

This differs quite a lot from "Memory: uses around 100MB of RAM, with peaks at around 200MB." & "Efficient: A small memory footprint [...]" from the readme, so I assume this is a bug?

**Comment by neilalexander** [comment]
This is more likely to be the fact that Go is not releasing memory back to the operating system, but instead using `madvise` to allow the operating system to reclaim it only if the memory is needed for something else. This can appear in tools like `top`/`htop` as inflated resident memory usage.

You can disable this behaviour by starting Go with the environment variable `GODEBUG=madvdontneed=1`. If you still have the problem with this environment variable set then we will consider it a bug. Otherwise, it's entirely possible this is working as intended.

**Comment by neilalexander** [comment]
Also, looking at your `RES` column, which is the relevant one here, your Dendrite is only using 500MB-ish RAM?

**Comment by Kegsay** [comment]
As @neilalexander this is a Go problem, they're reverting this behaviour in later Go versions - for context see https://github.com/golang/go/issues/42330 - in other words memory usage displayed in `htop` is not an accurate indicator of the real memory usage.

Please reopen if you believe this to be caused by something else.

**Comment by z3ntu** [comment]
Ah, thanks for the clarification then! It looks quite confusing :)

**Comment by cyberb** [comment]
My amd64 test instance is using 2g out of 8g ram.
I have only joined `#matrix:matrix.org` on it.
I thought this memory setting was changed in go v16, now I am on 19 and it does not look memory efficient to me. Is there an easy way to check what is taking memory?
![IMG_20230320_213836](https://user-images.githubusercontent.com/885528/226472131-5171eb3f-a566-4c33-baac-936d790f1a2b.jpg)
