### ISSUE TITLE
Erroneous M_UNKNOWN_TOKEN when supplying a ?user_id for a non-appservice

### ISSUE THREAD

**Issue by turt2live** [matrix-org/dendrite#1738]
The server should ignore the `user_id` query parameter if the token does not belong to a registered appservice. It appears as though Dendrite instead returns M_UNKNOWN_TOKEN.

**Comment by TheArcaneBrony** [comment]
This issue came up in [#matrix-spec](https://matrix.to/#/%23matrix-spec%3Amatrix.org/%243xdth-VMC-URku6BaJbUm3VNl2PH8knYr5HfCq038YU?via=matrix.org&via=element.io&via=envs.net&via=rory.gay)
The check in question appears in [user_api.go:564..572](https://github.com/matrix-org/dendrite/blob/bb2ab62cbf02abb6f600e6eb39fde67aa2ff3215/userapi/internal/user_api.go#L564-L572)

Would be nice to fix since this brings compatibility issues with libraries, especially our own.
