### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by AlphaJack** [matrix-org/dendrite#1772]
**Description:**

I just wanted to know if Dendrite will follow Synapse regarding [MySQL support](https://github.com/matrix-org/synapse/issues/2112#issuecomment-779181958) , or if we may see this feature implemented in the future.

[Gitea](https://gitea.io/) for instance uses [Xorm](https://xorm.io/) as Go abstaction layer, but it's a completely different kind of service.

**Comment by neilalexander** [comment]
We have discussed this in the past, and someone even created a PR to add MySQL support (#1105), but we ultimately decided that there was no benefit in adding MySQL support.

Ultimately it gives us nothing that PostgreSQL doesn’t already give us, but adding additional database backends does increase the codebase maintenance overhead significantly.

**Comment by AlphaJack** [comment]
Understood, thank you.

**Comment by GwynethLlewelyn** [comment]
> Ultimately it gives us nothing that PostgreSQL doesn’t already give us, but adding additional database backends does increase the codebase maintenance overhead significantly.

May I respectfully disagree?

The keyword on that sentence is **"us"**. I'm certain that these are no benefits to those who are part of **"us"**.

However, from the admin server's perspective, it means having to run and maintain Yet Another Database Server — which means allocating more resources (memory, disk, CPU power... _and_ humans too!). Depending on the organisation, this might be very easy (large organisations will probably be already maintaining several different database types, and the extra resources for handling another one is negligible) or very hard (there might be a limit to how many different database servers are able to be deployed simultaneously in the same systems by the same team — such a limit may be technological, but also administrative).

That said, I fully understand the difficulties of maintaining separate codebases for a plethora of database backends, or, alternatively, by employing an abstraction layer, the frustration of having to limit development to a small subset of SQL (the minimum common denominator for all possible SQL implementations and variations). None of these are easy choices to make — each with its drawbacks — and I totally respect your choice.

But be wary of sticking to one (well, two) database backend only. You don't want to go the way of WordPress — too closely linked to MySQL for two decades and too hard to change all the codebase, no matter how many layers of abstraction placed on top of it. There _are_ advantages of using a backend over others; for example, cloud providers might offer an interface to one kind of database but not to another, and offer cheap database access that way. Larger organisations might already have deployed an enterprise RDBMS (Oracle, DB2, MSSQL...) and prefer to focus the licensing costs on a single vendor and benefit from lower costs per user/server/database/whatever. Even if PostgreSQL is free and open source (and most certainly has industry-grade robustness!), it nevertheless incurs in the hidden cost of maintaining it — just like any other database server.

Also, it's worth considering non-SQL databases in the future as well — mostly for the sake of performance and network distribution with redundancy. 'Traditional' RDBMS have always been tough to configure as clusters — trading that requirement off for the easy of development using some dialect of SQL. Which, in turn, is another completely different issue: for lots of applications, SQL might not be the 'best' language to retrieve data anyway — either you need to do relatively simple queries with fast access (and for that SQL is not the best solution), or you need to do insanely complex JOINs and recursive SELECTs (and then the database server will struggle to complete such requests anyway), thus leading to code refactoring to avoid complex queries (and forfeiting the advantage of using SQL in the first place) anyway — and raising the question if SQL was the appropriate database retrieval language anyway (since you _could_ have used some database backend that is much smaller, fundamentally faster, and much more efficient in resource consumption — if you're just restricting yourself to simple queries anyway).

Anyway, my point is just that claiming that a particular RDBMS 'gives nothing that PostgreSQL doesn’t already give' is a quite  limited and closed statement that requires some qualification — or else it will be tautologically false. There are faster databases than PostgreSQL. There are more powerful ones. There are smaller ones. There are completely different technologies that don't even compare easily. There are more popular ones. There are those which require much less maintenance and tuning. The list goes on and on. When sticking to a specific vendor, it's worth listing _why_ one is stuck with it, and, as the project evolves, keep questioning if the underlying assumptions remain valid. In the case of Dendrite, the fundamental question is 'what is the tradeoff of sticking with PostgreSQL compared to using an abstraction layer that can be used with _any_ database, now and in the future?'

At the end of the day, it'll be like what happens on my small home NAS made by Synology: its Linux variant (vaguely based on a Debian distro) requires launching nothing less than PostgreSQL, Redis, Memcached, and a few that I haven't identified yet (they're proprietary). To access those backends, code is written in C/C++, Python, Perl, and even PHP. Every time a new 'feature' is added to the system, they usually need to add one or another additional database backend and/or language framework, because, well, new developers prefer tool X over Y. At the end of the day, the end-user will complain that 'the NAS runs too slowly'. It wouldn't _need_ to run that slow if there had been a decision, from the start, to stick to a backend that is more appropriate for a low-end ARM64 chip with just 1 GB of RAM, instead of trying to pretend that the hardware is a small datacentre-in-a-chip and expect it will support _all_ kinds of databases and frameworks, just, well, because it's Linux, and it can run anything that is open source, right?

Right.

Again, I'm not a die-hard MySQL/MariaDB fangirl. I used to be, in 1997, but not any longer. MySQL/MariaDB have serious shortcomings, the least of which is the huge footprint, rivalling some industry-grade installations, but without the performance expected from them. When MySQL started to gain some acceptance as a general-purpose, almost-enterprise-grade SQL RDBMs, we used to laugh at Oracle die-hard fans because they needed to read a 400-page manual with configuration options, and go through one by one, to fine-tune the RDBMS to a particular use-case — while MySQL just had a handful of easy-to-understand options and would run at top performance all the time. A quarter of a century later, MySQL (now owned by Oracle, of course) is as bad as Oracle was in 1997 — but hardly at the same level of performance. It's just much cheaper to run!

That said, no, I'm not entering a fight about what SQL backend is better, and why. Each has its advantages and disadvantages; and even a backend-neutral approach using an abstraction layer (so that _all_ databases can be supported!) has its disadvantages (plenty of them, in fact).

All I can say is that I find it somewhat ironic that the key component for the Matrix which allows so many different communication protocols to easily interconnect, by bridging across them, is then 'stuck' with a single database backend vendor (well, two, but SQLite doesn't really count :) )... I would expect a much more open approach to the issue, because it _is_ an issue.

**Comment by neilalexander** [comment]
If you'd like to take on the job of adding and maintaining support for MySQL and/or other databases on an on-going basis, may I suggest [applying for a job at Element](https://element.io/careers)?
