### ISSUE TITLE
Improve memory use

### ISSUE THREAD

**Issue by ptman** [matrix-org/dendrite#1805]
**Description:**

Dendrite can use a lot of RAM at times and this can result in it getting killed by the oom-killer.

Keywords: ram, memory, oom, resource use, efficiency, killed

**Comment by ptman** [comment]
#1804 could improve this a lot

**Comment by ptman** [comment]
Caching helps a lot in synapse https://github.com/matrix-org/dendrite/issues/1102

**Comment by Kegsay** [comment]
Caching bloats baseline memory, it doesn't help it. It helps reduce CPU cycles.

There are several problems which can cause Dendrite to gobble up memory:
- complicated state resolution. State resolution looks at historical state as well as the current state so older rooms or rooms with lots of membership churn will reduce performance because all those events need to be extracted from the database.
- resolving state with lots of prev_events. If a room has a lot of servers and they constantly fork the room, when the forks get merged we need to do state resolution. Even small rooms (with lots of forks) can reduce performance due to needing to extract the events multiple times. We can probably improve this with an event cache so we can have pointers to the same structure.

An "easy" fix to all this is to not federate, as all these issues only appear once you start doing state resolution which only happens when servers disagree or need to work out the room state.

**Comment by ptman** [comment]
Yes, caching uses more memory. But counter-intuitively it does sometimes help with synapse, as the cached result uses less memory than the process of re-calculating the value.

**Comment by neilalexander** [comment]
It would be interesting to get some feedback on how much recent changes have helped here. Version 0.4.0 specifically contains some pretty huge improvements on memory usage, especially when dealing with incoming federation events, calculating memberships and running state resolution, so hopefully it is noticeable.

**Comment by neilalexander** [comment]
@ptman I'd be curious to know if you think this is still a problem, especially given recent optimisations in v0.6.x. There are also additional things that have been merged onto `main` today that should help even more (#2226, matrix-org/gomatrixserverlib#292). I'd like to close this if it's no longer a noticeable issue.

**Comment by ptman** [comment]
Sorry, I lost my dendrite installation. I'll have to deploy a new one at some point when I have a chance. I'll close this for now.
