### ISSUE TITLE
Add a -o option to Mono/Poly Dendrite to dump logs to a file

### ISSUE THREAD

**Issue by yaliqmadiq** [matrix-org/dendrite#1820]
I tried running mono with redirect to file and that's no dice.

In order to solve issues like go-routine leaks in production, you need to SIGHUP a running server to get at the goroutine stack dumps which in some cases can pump out thousands of lines of console output.

There's a very small number of terminal emulators that can buffer that much, or you have to be a wiz at copying out of tmux screen by screen of STDOUT to capture those dumps.

So it makes sense to add a -o {filename} startup parameter and update the logger to dump into a file to make this easier.

**Comment by Kegsay** [comment]
We already support logging to file. If you require more than this (e.g because you are SIGHUPing and that splats to stdout) then that's up to you to capture/log stdout. If you're running in docker this is done for you. If you're running in a screen, you can use `screen -L` to automatically log screen output to file.
