### ISSUE TITLE
Excesssive resource usage during avatar update

### ISSUE THREAD

**Issue by gleachkr** [matrix-org/dendrite#1937]
### Background information

- **Dendrite version or git SHA**: 728061db0320f578eebc3d249bdca46ee49fe219
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**: No
- **`go version`**: go1.16 linux/amd64

### Description

Dendrite has a CPU storm, and leaks memory when I change my avatar - eventually, this causes a lockup or OOM.

### Steps to reproduce

Note: federation is disabled in dendrite.yaml

- `bin/dendrite-monolith-server --tls-cert server.crt --tls-key server.key --config dendrite.yaml`
- Repeatedly change an avatar, observing CPU and memory usage - memory usage climbs by about 75M with each change, and there's a CPU spike to 80%, lasting about 15 seconds, on a minimal DO droplet with 1GB memory.
- Eventually,  reach the memory ceiling, at which point the CPU doesn't cool off, and locks in around 100%. This continues until OOM or manual restart. Dendrite is still a little bit responsive, but stops serving the media store.

With each CPU storm, dendrite spawns a large number of messages of the form:

```
INFO[2021-07-22T21:58:00.296131897Z] [roomserver.go:102] onMessage
	 Federation disabled                           error=new_room_event
INFO[2021-07-22T21:58:00.327058475Z] [input.go:130] WriteOutputEvents
	 Producing to topic 'DendriteOutputRoomEvent'  adds_state=1 content_value=join event_id="$wPByJLDJkpHuYmrXDk2Y80Bo2IXb9tKPgwEz-eZAXIM" event_type=m.room.member removes_state=1 room_id="!TaivgiDeV9N2QkZ0:..." send_as_server=... sender="@graham:..." state_key="@graham:..." type=new_room_event
```

CPU and Heap profile available, let me know if those would be helpful.

**Comment by kegsay** [comment]
CPU and heap profiles would both be useful. Please DM me at @kegan:matrix.org

Changing your avatar or display name results in a membership event being sent into every room you're joined to. How many rooms are you in?

**Comment by kegsay** [comment]
```
(pprof) top3 
Showing nodes accounting for 5450ms, 64.96% of 8390ms total
Dropped 466 nodes (cum <= 41.95ms)
Showing top 3 nodes out of 270
      flat  flat%   sum%        cum   cum%
    4330ms 51.61% 51.61%     4430ms 52.80%  runtime.cgocall
     670ms  7.99% 59.59%     1320ms 15.73%  runtime.scanobject
     450ms  5.36% 64.96%      460ms  5.48%  runtime.findObject
```

<img width="685" alt="Screenshot 2021-07-23 at 17 10 44" src="https://user-images.githubusercontent.com/7190048/126810904-889d5237-06b3-494d-a18e-9d0adbcd561b.png">

Given this is a no-federation server, I wouldn't expect us needing to do actual state res here. Is the common case of single-state updates pulling all the events for the room? cc @neilalexander

**Comment by kegsay** [comment]
`LoadStateAtSnapshot` just returns the NIDs for event type / state key / event ID, so we really shouldn't be loading all the state events.

**Comment by neilalexander** [comment]
> Given this is a no-federation server, I wouldn't expect us needing to do actual state res here. Is the common case of single-state updates pulling all the events for the room? cc @neilalexander

Well, state resolution happens in either/both of the following cases:

* The event has multiple `prev_events`, in which case state resolution is used to calculate the state before the event when we persist it to the database
* The room has multiple forward extremities, in which case state resolution is used to calculate the current room state across all the extremities

I suppose it's not terribly likely that there would be multiple forward extremities on a non-federating server, in which case we're basically dealing with a single state set. I have a feeling state events may still be loaded into memory for the second case though as there's probably a difference in state before vs state after the new event.

@gleachkr — can you please confirm in your `roomserver_rooms` table whether there are any rows in the `latest_event_nids` which contain more than one NID?

> It's an interesting failure mode because changing the profile will send an event into every room you're joined to, which causes `DifferenceBetweeenStateSnapshots` which will load the entire room state (albeit as optimised integers) twice for each room (the previous latest state and then the state after applying the profile change). 

We start off loading the room state as NIDs but we then have to load the actual state events themselves to run state resolution when the forward extremities are updated. We can't run state resolution using the NIDs alone.

> We could perhaps set an upper bound on the concurrent room workers?

The issue mentions that this is running with SQLite, in which case we aren't running with concurrent room workers anyway. That possibly prolongs the problem, since the updates will happen in serial and that's likely taking up quite a bit of the roomserver's time.

**Comment by kegsay** [comment]
> in which case we aren't running with concurrent room workers anyway

Then why do we keep consuming memory I wonder. A memory leak somewhere?

**Comment by gleachkr** [comment]
> @gleachkr — can you please confirm in your `roomserver_rooms` table whether there are any rows in the `latest_event_nids` which contain more than one NID?

Hm, I don't think so. there are 209 rows, each of the form `[####]` for 3 or 4 digits `####`

**Comment by neilalexander** [comment]
The roomserver inputs have been refactored a whole bunch of times since this issue so I'm going to close it for now, please reopen if there is still an obvious issue with 0.8.1.
