### ISSUE TITLE
I can't change my profile pic ever since we migrated to dendrite

### ISSUE THREAD

**Issue by r3k2** [matrix-org/dendrite#2037]
Dendrite version:
latest master from today
postgresql
mono
around 129 users
more info:
https://matrix.hispagatos.org/_matrix/client/versions
---
Issue:
I was never able to really change my profile picture and in some places it shows the old one I had when we were on sypnapse last year... this is not much a big deal but very annoying 
this only happens to me as far as I can tell since I saw other users been able to change their profile pic.

```
time="2021-11-02T18:55:58.333789220Z" level=error msg="helpers.CheckAuthEvents failed for event, rejecting event" func="github.com/matrix-org/dendrite/roomserver/internal/input.(*Inputer).processRoomEvent" file="github.com/matrix-org/dendrite/roomserver/internal/input/input_events.go:106" auth_event_ids="[$PBb6leU9oLwdu5o9Dru9VpFpvyjoOpTj-slAxXwjIVM $-_GjB6rMHYs85C96tF7sVORNBHkorQrOJLiuqX3KCVg $2i2_jSL_pt7qcd6f1f4c0XObsxff8NrzYDchN9I3x64 $mac46vo2aw6XcuKQU4uxDCnUqZzhLFkeopHmVq3TvpA]" error="eventauth: \"@rek2:hispagatos.org\" is not allowed to change their membership from \"leave\" to \"join\"" event_id="$XJpwN62YM8w8eEQqPQfhbJshJqRthcURFwxggCF28CU"
```

we host around 50 or so channels
one of them is only local/non-federated.

when I do this from element-browser I get the msg above
when I do this from element android it crashes the server I have to restart dendrite.. no error.

**Comment by kegsay** [comment]
Changing profile pictures sends an `m.room.member` event into the room, with the same membership state (joined) but with a different `avatar_url`. Sometimes Dendrite disagrees with other servers on the membership state of a user in a room, this seems to be what's happening here. Dendrite believes `@rek2:hispagatos.org` isn't in the room, and it shows you the reason why (the auth events listed). Based on this message, this is most likely because the `join_rule` for the room is `invite`.

I this _particular_ case, you may find that leaving the room and getting re-invited to the room will resolve this issue. This is still a valid issue however, as Dendrite should be able to work out the membership state correctly.

**Comment by r3k2** [comment]
Hello @kegsay thanks again, yes indeed I left the room and someone else re-invited me and now at least I can see the profile pic.

**Comment by kegsay** [comment]
This is general federation woes and this issue lacks details necessary for more debugging. Closing.

**Comment by MadLittleMods** [comment]
Related to https://github.com/matrix-org/dendrite/issues/1662
