### ISSUE TITLE
Please publish binaries with releases

### ISSUE THREAD

**Issue by 08d2** [matrix-org/dendrite#2275]
It would be helpful if published releases e.g. [0.6.5](https://github.com/matrix-org/dendrite/releases/tag/v0.6.5) included binaries for supported platforms, even if that's just linux/amd64 for now. I appreciate that you're publishing Docker images, but binaries are more widely usable.

**Comment by ealib** [comment]
The availability of precompiled Dendrite binaries would be particularly important for Windows users, of course.

**Comment by ealib** [comment]
For reference only, other projects written in Go that release pre-compiled binaries for various platforms supported by the toolchain:

* [Caddy](https://github.com/caddyserver/caddy/releases)
* [Gitea](https://github.com/go-gitea/gitea/releases)

Furthermore, for full integration in Windows, where background processes have to comply with certain rules in order to be compatible with the *Service Control Manager*, the easiest way seems to be to use the [Minimal windows service stub](https://pkg.go.dev/github.com/kardianos/minwinsvc).

**Comment by ealib** [comment]
I forgot that the very [NATS](https://nats.io/) publishes

* [NATS server pre-built binaries](https://github.com/nats-io/nats-server/releases)
* [NATS Windows Service](https://docs.nats.io/running-a-nats-service/introduction/windows_srv)

**Comment by kegsay** [comment]
We are not planning on supporting binaries with releases at this time. We already have docker images with different architectures. We are a very small team and are sadly unable to maintain a comprehensive release setup, as the cost of this would be too great as we'd need to ensure binaries don't have regressions _in addition_ to the Docker releases which we actively use and test.

We may revisit this in the future.
