### ISSUE TITLE
_matrix/client/unstable/org.matrix.msc2432/rooms/:room_id/aliases CORS issue

### ISSUE THREAD

**Issue by thepra** [matrix-org/dendrite#2570]
### Background information

- **Dendrite version or git SHA**: 0.8.9
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.18.1
- **Client used (if applicable)**: Cinny

### Description

 - **What** is the problem: 
This endpoint `/_matrix/client/unstable/org.matrix.msc2432/rooms/:room_id/aliases?access_token=<redacted>` is being called from a subdomain where the client lives(`chat.<DOMAIN>`, meanwhile the server at `<DOMAIN>`) and it's the only call that have CORS issues about Access-Control-Allow-Origin missing despite it is already set as a `proxy_set_header Access-Control-Allow-Origin '*';` in nginx.

Is this a bug?

**Comment by neilalexander** [comment]
In this instance, you are seeing a CORS error because the endpoint does not exist in Dendrite.

Seeing as MSC2432 was merged into the spec back in 2020, Dendrite instead implements the stable endpoint at `/_matrix/client/r0/rooms/{roomId}/aliases`.

You should raise a bug with Cinny about incorrectly using an unstable endpoint for a stable feature.

**Comment by thepra** [comment]
@neilalexander thanks for the answer :)
I did open an issue at cinny
