### ISSUE TITLE
Dropped Rooms/Spaces on Incremental Syncs

### ISSUE THREAD

**Issue by timaeos** [matrix-org/dendrite#2660]
### Background information

- **Dendrite version or git SHA**: 0.9.4+9dc57122d991d54ea6750448ba88c8763a569830
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.19
- **Client used (if applicable)**: Element desktop

### Description

 - **What** is the problem: After upgrading the server to 0.9.4+9dc57122d991d54ea6750448ba88c8763a569830 rooms and spaces that I'm a part off started dropping/ Invitations to previously joined private rooms persisted and could not be re-joined
 - **Who** is affected: Clients on my server
 - **How** is this bug manifesting: There aren't any visible errors in the logs. Attempting to join one of the rooms that dropped in the client results in a successful join message in the dendrite logs but the Element client never successfully joins. The only way to fix it on the element desktop client is a `clear cache and reload`. After performing the `clear cache and reload` it's fine for a time but some amount of time later, it drops the same rooms again. Another `clear cache and reload` fixes it again. It seems like there might be a race condition introduces somewhere?
 - **When** did this first appear: After upgrading dendrite to 0.9.4

### Steps to reproduce

- Have an account on the dendrite server that is already joined to a restricted space and rooms with restricted joins
- Upgrade to 0.9.4+9dc57122d991d54ea6750448ba88c8763a569830
- Log into an account with Element version: 1.11.3 Olm version: 3.2.12
- Monitor for drops from previously joined spaces/channels

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
Clients expect previously joined rooms to persist. @jjj333-p also experienced the same behaviour after the upgrade to 0.9.4 and had to revert to 0.9.3 to prevent the behaviour.

Below is an example of a join attempt after the rooms had dropped in element. 

```
Aug 19 12:16:12 hermes dendrite-start.sh[2123733]: time="2022-08-19T17:16:12.355306985Z" level=info msg="User requested to room join" room_id="#hatnix:tchncs.de" servers="[tchncs.de]" user_id="@timaeos:matrix.nexaeos.io"
Aug 19 12:16:12 hermes dendrite-start.sh[2123733]: time="2022-08-19T17:16:12.964364405Z" level=info msg="User joined room successfully" room_id="#hatnix:tchncs.de" servers="[tchncs.de]" user_id="@timaeos:matrix.nexaeos.io"
```

Originally I thought that it had something to do with the a race condition in with the deletion of the `newlyJoinedRooms` in #2657 but that's not clear to me at this point since it seems to intermittently happen on incremental syncs.

I haven't been able to recreate it deliberately since 08/19/2022 which is what lead me to believe it might be a race condition.

**Comment by jjj333-p** [comment]
For me at least this was not a client specific bug, as i got it on both element web (develop.element.io) and the latest element ios (which i know isn't the best standard as it barely even follows spec, but it clearly is different). I had my homeserver on Dendrite 0.9.4+9dc57122 (the same dendrite and go version as timaeos i believe) when this issue was occurring 

When this bug would happen not only would spaces dis appear for me, but I would also have about 20 of my 50+ rooms disappear. During this time it also seemed that the client would not be able to receive any messages and would be either laggy or fail to send messages. This issue would go away when the client's cache was cleared so perhaps this bug is something to do with trying to sync from what had last been synced.

Even when this bug wasn't occurring, this update seemed to make my server feel much laggier sending and receiving messages, and after downgrading back to Dendrite 0.9.3+bcdbd5c0, all the above issues have gone away

**Comment by jjj333-p** [comment]
oh also only one of my spaces ever remained, it was https://matrix.to/#/#skill-issue:jameskitt616.one

**Comment by neilalexander** [comment]
@S7evinK Do you mind having a look into this and seeing if there are obvious reasons why these rooms/spaces might be incorrectly appearing in the `”leave”` section?

**Comment by jjj333-p** [comment]
if it helps anyone, i just tested it earlier this morning, and the issue persists on 0.9.4+78e5d05e

**Comment by S7evinK** [comment]
What I'm really wondering is, if it's really related to #2657 (https://github.com/matrix-org/dendrite/commit/9dc57122d991d54ea6750448ba88c8763a569830), because that would only "trigger" in incremental syncs if you've joined a new room/space. Is 0.9.4 (https://github.com/matrix-org/dendrite/commit/56b55a28f591cd2e920c5f16bee6f7a97b0898c0) working without issues? Which version were you on before upgrading to 0.9.4 (9dc57122d991d54ea6750448ba88c8763a569830)?

**Comment by jjj333-p** [comment]
This bug doesnt seem to occur depending on joining rooms, it literally is like 90% of the time when like i put my device to sleep or relaunch the client or whatever and it syncs from the point that it was last online.

The "stable" version that i keep returning to is 0.9.3+bcdbd5c0

should i attempt to install 56b55a2 and see if it works without issues?

**Comment by S7evinK** [comment]
That would be awesome if you could do that. But I might already have a clue/an idea about what's wrong, given you are in 50+ rooms.

**Comment by jjj333-p** [comment]
okay i am fairly noob to git, how would i clone that specific commit?

**Comment by S7evinK** [comment]
If you've already cloned the repo, you can do a `git checkout 56b55a28f591cd2e920c5f16bee6f7a97b0898c0`, once done testing you run `git switch -` and you're back to the state before the checkout of that specific commit.

**Comment by jjj333-p** [comment]
![image](https://user-images.githubusercontent.com/94018608/186347058-0e6d3b1f-27a5-402f-8700-97aa2f885727.png)

ill put my laptop to sleep, and fuck around with matrix for a bit and ill tell you if it has issues.

**Comment by jjj333-p** [comment]
okay so far it seems to not be having any issues. of course i will update if any come about but it seems that commit does not have the issue

**Comment by neilalexander** [comment]
Is this still a problem on 0.9.5?

**Comment by timaeos** [comment]
I haven't experienced a problem on 0.9.5 yet. I think it was happening more frequently to @jjj333-p than to me, however. I saw that @S7evinK had reverted the commit so it's possible it could be gone altogether. I think we can close this issue once @jjj333-p confirms they're not seeing it anymore after the 0.9.5 upgrade

**Comment by jjj333-p** [comment]
Can confirm, I have been running 0.9.5+ed79e862 and it doesn’t seem to have
this issue.

**Comment by S7evinK** [comment]
Most likely caused by #2657 (now reverted), as we we're getting newly joined room data already in a different place.
