### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by onlineapps-cloud** [matrix-org/dendrite#3019]
hi, i had error: `This file is too large to upload. The file size limit is 0 B but this file is 15.98 kB.`
![image](https://user-images.githubusercontent.com/69077240/226172961-213a6438-0ee9-4b63-9367-9b0472c9353e.png)

dendrite version:  0.12.0

in dendrite.yml say:

```
  # The maximum allowed file size (in bytes) for media uploads to this homeserver
  # (0 = unlimited). If using a reverse proxy, ensure it allows requests at least
  #this large (e.g. the client_max_body_size setting in nginx).
  max_file_size_bytes: 0
```
i set value to 0 , but not working with this value. I don't use reverse proxy.
i changed to 1073741824 bytes(1GB), and work, but 0 value not work.

**Comment by S7evinK** [comment]
Can you try with the latest [commit](https://github.com/matrix-org/dendrite/commit/0459d2b9e586b53d0ffc9f362f1dcd42b79995f5) on main? I guess since we returned `null`, the react-sdk didn't think of it being [undefined](https://github.com/matrix-org/matrix-react-sdk/blob/bc60e59eda904fd35a0b7c3f5b6a041114e45034/src/ContentMessages.ts#L592-L601) and thus returned e.g. `10 > null` -> `true`.

**Comment by onlineapps-cloud** [comment]
problem fixed, now working with `0` value.
