### ISSUE TITLE
Include hardware requirements in the README

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#324]
There isn't much point in doing this until dendrite is actually usable, as the requirements now probably won't accurately reflect the requirements down the line

**Comment by neilalexander** [comment]
At the moment my Dendrite homeserver monolith process is using, on average, 100MB RAM and then Postgres is using about 300-400MB RAM. The highest I've seen the monolith process use recently is about 160MB. Postgres is using about 1.7GB disk space after a couple of months and that's also including Naffka weight. CPU-wise, Dendrite does spike CPU usage briefly when processing events but otherwise sits at less than 1% idle utilisation on a quad-core VM. There's roughly 2.5 hours of CPU time since I restarted the process a few hours ago.

That's pretty much as a single user, joined to 10 reasonably sized channels, one or two of those with encryption, and a handful of other DMs.

It's difficult really to write hardware requirements without understanding target scaling, but since we manage to run Dendrite quite happily on iPhones and in web browsers, I would suggest that the single-user requirements are reasonably low. Obviously for a significant number of users, we'll start to see more resource consumption but I can't really predict what that is yet.
