### ISSUE TITLE
AckAllPolicy may be a bad choice for RoomConsumer?

### ISSUE THREAD

**Issue by iamblinking** [matrix-org/dendrite#3240]
thouthands of msgs are still in InputRoomEvent queue after msg were processed and acked

**Subjects:**
![image](https://github.com/matrix-org/dendrite/assets/5259808/59f34a40-67de-449f-b861-58cab2fd1101)

**Stream info**
![image](https://github.com/matrix-org/dendrite/assets/5259808/236a4521-ebe2-43d7-9721-9af6b6c88705)

**Consumer info**
![image](https://github.com/matrix-org/dendrite/assets/5259808/5784ca9e-99c7-4614-b50e-5c32f09c8d38)

**question**
Since msgs were processed and acked successfully, it's possible the AckAllPolicy's problem.
After I   changed AckPolicy from AckAllPolicy to AckExplicitPolicy, problems disappear.

**Comment by iamblinking** [comment]
larger waitAck will solve this

**Comment by iamblinking** [comment]
change AckPolicy will solve this.
![image](https://github.com/matrix-org/dendrite/assets/5259808/16dcc512-7dc1-432b-82a3-d2d868d8b0d4)

**Comment by iamblinking** [comment]
I have questions below.
1. Each room have its consumer to process, why we use AckAllPolicy to ack other room's msg?
2. msgs of small sequence belong to room2,  if room1 ack them, maybe they are still processing?

**Comment by S7evinK** [comment]
Labeled as `S-Major`, because I do believe that this may also be a cause for state resets happening.

My personal instance has been "reprocessing" (I assume) the same event over and over again, even though it was already processed (as it was received by the SyncAPI)

Currently testing your fix and looks good so far. The issue kicked in after some hours before.
