### ISSUE TITLE
Load Dendrite configuration from multiple hierarchical sources

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#393]
Yan Minari:

[...] the config file should be optional, setting the server address using env vars should be a thing, etc

1. load sane defaults (hardcoded on binary)
2. override with config file (if any)
3. override with --flags
4. override with env vars
5. override with secret file
6. etc.

not exactly everything in this list or in this order but you get the idea

**Comment by yangm97** [comment]
More on that: https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c

**Comment by CromFr** [comment]
I'm currently looking at this issue :)

This is what I'm planing to do for configuration loading:

Configuration is build from multiple sources. Each override replace scalars and arrays with the provided value, mappings are only looked recursively (seems to be `gopkg.in/yaml.v2` default behaviour).

Here are the configuration sources:

0. Compiled default config. Should produce obvious errors when users don't override those value (ie panic & print "you must set matrix.server_name" if not present)
0. System configuration file (ie `/etc/dendrite.yaml`). Fallback to an empty file if not found.
0. Configuration file provided as command line argument (`--config`). Two approaches here:
    1. Try to open `dendrite.yaml` and fallback to an empty file if not found (eventually post a warning). If a config path is provided as command-line argument, panic if not found.
    2. Use an empty file if no config file is provided by command-line (no more `dendrite.yaml` used by default). If a config path is provided as command-line argument, panic if not found.
0. Command-line argument, with `--set` option, that can be provided multiple times. The value format should be valid yaml (seems a legit choice since config is in yaml and you can inline anything using json syntax):
    - `--set='matrix.server_name: example.com'`
    - `--set='matrix.trusted_third_party_id_servers: [vector.im, matrix.org, riot.im]'`
0. Override with a single environment var
    - `DENDRITE_CFG='{matrix.server_name: example.com, media.base_path: /dev/null}' dendrite-room-server`
0. Any ideas? (I didn't get what @anoadragon453  meant by "secret file")


I think this cover most use cases, but we could eventually add specific syntax like (not very useful IMO):
- `matrix.trusted_third_party_id_servers+: [ example.im ]` append elements to an array
- `matrix.trusted_third_party_id_servers-: [ riot.im ]` remove elements from an array

---

Some other ideas:
- Allow to provide multiple `--config=file` arguments, so the starting config is build using multiple configuration fragments

**Comment by ptman** [comment]
For me it would feel more natural if command line flags would override environment flags. You can launch several instances in the same environment, but the flags are specific to the instance, so it should be the more specific option.

**Comment by yangm97** [comment]
@ptman in a docker deployment it’s easier to change env vars than it is to change flags. For instance, some of my applications are deployed using GitLab CI, changing a flag would require a new commit, changing an env var only requires me to click to run the CI routine again. 

Besides, I think most projects work like this, so going against it could be counter intuitive. At least the ones I know, bear in mind I _am_ biased 😆

**Comment by ptman** [comment]
I'm familiar with docker. Usually I just make sure that I have no command-line flags so that I can override the config with environment variables. In my experience this is what is expected in UNIX-like environments. E.g. from the [python documentation](https://docs.python.org/2/using/cmdline.html): "It is customary that command-line switches override environmental variables where there is a conflict."

**Comment by Kegsay** [comment]
So this was discussed when we had dendrite architecture talks a few weeks ago. I'm a strong proponent of env vars simply because Docker. A lot of the microservices just use simple scalars which map well to env vars. For arrays, flattening them kinda sucks. Likewise for dictionaries. 

The conclusion was to refactor the config into smaller components (#889) then have a look to see how bad allowing env vars would be.

**Comment by feffes** [comment]
I think it might just be best to axe everything but environment variables for now, with the goal of having one source for all configs that can be easily changed while developing. 
It would make introducing new configs easier while we're still in active development.
If people feel it would be nice to have flags and yml-files for config it could be reintroduced when we're closer to a stable release, in which case we should attempt to ensure feature parity with the env-var configs.

**Comment by yangm97** [comment]
Just use [viper](https://github.com/spf13/viper).

**Comment by Kegsay** [comment]
Work is progressing on this in https://github.com/matrix-org/dendrite/pull/1230
