### ISSUE TITLE
Support other database backends

### ISSUE THREAD

**Issue by Ronsor** [matrix-org/dendrite#506]
It would be great if other database backends, such as SQLite or ql were supported too. I'd rather not have to install postgresql and configure it just to run a homeserver, it seems like a lot of extra hassle.

**Comment by anoadragon453** [comment]
Postgres does provide far and away much more powerful features than SQLite though. It was one of the things holding back performance in Synapse.

Running postgres on a Linux or Mac system is fairly trivial. Simply grab it through your package manager, then run the two commands in INSTALL.md: https://github.com/matrix-org/dendrite/blob/master/INSTALL.md#configuration

**Comment by t3chguy** [comment]
+1 to not kneecapping Dendrite to make it work with "simpler" databases.
Synapse has a lot of postrges vs sqlite special casing to avoid this and is barely usable with sqlite in a standard federated scenario anyway.

**Comment by shazow** [comment]
FWIW, there shouldn't be much special-casing involved. If there's a commonly shared Store interface without SQL-specific abstraction leaks, then we could provide an implementation of it using sqlite or whatever else as desired (badgerdb etc). 

People who only want to try out Matrix with a few friends can use an embedded database to give it a try, and migrate to Postgres once the server is sufficiently popular.

Imagine a scenario where you could just do:

```console
$ go install github.com/matrix-org/dendrite
$ dendrite
```

And you have a fully functioning Matrix servers with no additional moving pieces. :)

**Comment by t3chguy** [comment]
right but then you can't write optimized queries?

**Comment by shazow** [comment]
@t3chguy Why not?

**Comment by t3chguy** [comment]
If you use some off-the-shelf common Store interface you'll be at its whimsy on how it actually builds your queries, often not optimally for your given schemas.

**Comment by t3chguy** [comment]
if you make your own then you *are* special casing by implementing this interface N times for each supported DBMS

**Comment by t3chguy** [comment]
I'm not saying special casing as in nasty code, I'm saying having to design every schema and sql query for each supported DBSM, implementing it by abstracting behind an interface is sane for this

**Comment by t3chguy** [comment]
Right of course, I assumed that was implied. But you still have to end up having to do a lot of extra work in the SQLite implementation of such a Store interface to feature-match it, and if you end up federating it'll likely get overwhelmed and underperform, as Synapse did

**Comment by t3chguy** [comment]
Currently, having Synapse ship with SQLite default yields people to have a bad experience of Matrix as soon as they try and join a large room, because it slows to a crawl

**Comment by shazow** [comment]
> Right of course, I assumed that was implied. But you still have to end up having to do a lot of extra work in the SQLite implementation of such a Store interface to feature-match it, and if you end up federating it'll likely get overwhelmed and underperform, as Synapse did

That's exactly right--the people who care about the other backends can maintain their own backends. People who want to federate and need additional performance can use whatever backend meets their needs.

This issue is about supporting other backends, not about making the current backend worse. It's not even specific to SQLite. In my mind, all this issue is asking is a cleanup of the code so that other backends *could* be written by people who want them.

Also worth noting that querying performance is a complicated topic that often exceeds the features of a specific database. It's quite possible that even SQLite could outperform PostgreSQL in specific cases. For example, I could run SQLite completely in-memory which would likely outperform any fancy on-disk PostgreSQL query.

> Currently, having Synapse ship with SQLite default yields people to have a bad experience of Matrix as soon as they try and join a large room, because it slows to a crawl

That issue can be addressed directly. Off the top of my head:

1. Could restrict federation with slow backends 
2. Could even issue a message/warning when certain queries start to take longer than some SLOW_TIMEOUT threshold and recommend using a different backend.

**Comment by erikjohnston** [comment]
Its worth noting that the storage is abstracted behind interfaces with the idea that we could support different storage backends eventually; though this is not a priority.

We specifically didn't want to try and write "generic" SQL queries that would work across platforms, as the experience of targeting both SQLite and postgres in Synapse showed that there are many cases where the syntax are subtly different for a given feature (e.g. AUTOINCREMENT vs AUTO_INCREMENT). Down the line people may try and write a generic SQL backing store.

(The performance differential between sqlite and postgres is a bit moot, since the idea is that you'd just shard or spin up more components.)

**Comment by Kegsay** [comment]
Well kids, this happened when we added SQLite support, which is relied on for p2p WASM. There's storage interfaces for each component, no shared queries.

Yes, it adds extra work every time we want to modify the storage layer, which makes general dev that much slower. We're still refactoring this to make this as painless as possible (eg statement sharing like naffka does, sqlx for reduced boilerplate) so we'll see how this progresses.
