### ISSUE TITLE
[discussion] Make processRoomEvent concurrent for different rooms

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#547]
I have a feeling that `processRoomEvent` can be called once at a time for a roomID, but concurrently for different rooms ?
https://github.com/matrix-org/dendrite/blob/d4b24462d19eb0a994f7b8af319d720e865a695c/src/github.com/matrix-org/dendrite/roomserver/input/input.go#L64-L66

original issue #375

**Comment by anoadragon453** [comment]
I would assume that processing concurrent rooms would be fine as room events don't depend on events from other rooms. @erikjohnston's original issue seems to suggest that it may be possible to even do a single room's events concurrently, but would that be possible since it needs to calculate deltas? Also how does the new delta state resolution ideas affect this?

**Comment by Kegsay** [comment]
Mutex per room for now will be fine.
