### ISSUE TITLE
Save room details in the publicroomsapi DB if created with the "public" visibility preset

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#603]
If a room is created using `"visibility":"public"`, save its details in the publicroomapi component's database so it's listed in responses for `GET /publicRooms`.

Not sure about the best way to do it, since the publicroomapi component is pretty independent and handles its own endpoints. The easy solution would be to make the clientapi component hit `PUT /_matrix/client/r0/directory/list/room/{roomId}` when creating a room with that preset, but that doesn't sound great performance-wise. We could also create a kafka topic the clientapi component would publish to and the publicroomsapi component would consume from.

That's just my thoughts about it, feel free to shout if I missed something.

**Comment by anoadragon453** [comment]
I believe we'd use a HTTP call to `/api/...` that we usually use for communicating between components?

**Comment by prateek2211** [comment]
I want to work on this one. 
Though, I am not sure what would be more plausible: new kafka topic or setting up an internal API

**Comment by Cnly** [comment]
I'd +1 on an HTTP API. Using kafka on this sounds a bit overkill.

**Comment by prateek2211** [comment]
@Kegsay should i go with setting up internal API?
what's your say on this?

**Comment by Kegsay** [comment]
I was just going to state my answer but then people don't learn. So here's how I worked it through.


In general, a good rule of thumb is to try not to increase your API surface. Bigger surfaces are more error prone (interactions between public functions, calling functions at the same time), harder to maintain (more code) and less clear how to use from an end-user perspective (if there's 4 ways to set the published flag, which one do you use?).

If we absolutely have to add a new API somewhere I'd be asking myself the following questions:
 - Does the component already have a consumer / internal HTTP API?
 - Does the component need to respond with data, or is it just reading?
 - Does the component need to process inputs in a well-defined order or replay inputs?
 - Does the component need to split inputs to allow for sharding?

For the publicroomsapi:
 - We already have a consumer which consumes roomserver events. We don't currently have any internal HTTP API for the publicroomsapi.
 - We just need to read data.
 - We need to process the published flag in order eg when you toggle it, but otherwise no particular order is needed. We don't need to replay events.
 - We don't need to shard this.

It's not clear which is better, which is why there's confusion. However, @babolivier had it right from the start.

> The easy solution would be to make the clientapi component hit `PUT /_matrix/client/r0/directory/list/room/{roomId}` when creating a room with that preset

We need to have that API anyway, so reusing it is easy and clear. "Performance" as a broad counter point is vague, amorphous and completely premature. Remember that Dendrite functions primarily to horizontally scale with load. *Even if* performance were a concern, the design and architecture means you can just add more services: all it means is that, per unit service, you can do slightly less work or slightly more work depending on how performant that component is. In this particular case, performance is a crazy counter point because:
 - People don't invoke this API frequently.
 - You need *some form* of communication: you cannot avoid that. Kafka would likely be *slower* because of needing to bounce via Kafka to persist the message.

So overall, just hit `PUT /_matrix/client/r0/directory/list/room/{roomId}` when creating a room with that preset.

**Comment by Kegsay** [comment]
It's worth noting my first answer was "hang on, surely there's a state event to indicate if a given room is published in a directory?" in which case you can just read that from the consumer that we already have. Sadly, there is no such state event, which feels a bit weird to me but oh well.

**Comment by prateek2211** [comment]
That helped a lot. Thanks!

**Comment by Kegsay** [comment]
#1174
