### ISSUE TITLE
Fix alias deletion

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#654]
- [ ] Keep track of an alias's owner (someone else shouldn't be able to delete an alias I set)
- [ ] `DELETE /directory/room/{roomAlias}` should 404 if the alias doesn't exist

**Comment by anoadragon453** [comment]
> Keep track of an alias's owner (someone else shouldn't be able to delete an alias I set)

Apparently this is an [implementation detail](https://matrix.to/#/!YkZelGRiqijtzXZODa:matrix.org/$15614741096174Svjyb:maunium.net?via=matrix.org&via=matrix.allmende.io&via=amorgan.xyz), so we could either prevent room admins from deleting aliases or allow it.

We could also provide a config option for dendrite to let the homeserver admin choose to allow server admins this ability.

**Comment by Cnly** [comment]
I'll say that we should always allow room and homeserver admins to delete aliases, even if they'll only be able to delete the local ones. This is their control over the room/server. The fact that admins can't remove alias mappings on other servers anyways *is* making their deleting local aliases less meaningful, but I don't think it makes enough sense either that we remove admins' control over local data because of this.

**Comment by anoadragon453** [comment]
[The spec](https://matrix.org/docs/spec/client_server/unstable#room-aliases) says we have free reign here, so let's go for allowing admins to remove local room aliases.
