### ISSUE TITLE
Investigate server apparently looking for a signature from itself

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#666]
The sytest test `Can invite unbound 3pid over federation with users from both servers` seems fails, apparently because Dendrite looks for a signature from itself, according to the logs, which doesn't make much sense. We should investigate.

**Comment by neilalexander** [comment]
This is likely because invite events over federation need to be signed both by the inviter and the invitee, [as per the spec](https://matrix.org/docs/spec/server_server/r0.1.3#put-matrix-federation-v1-invite-roomid-eventid):

> Invites a remote user to a room. Once the event has been signed by both the inviting homeserver and the invited homeserver, it can be sent to all of the servers in the room by the inviting homeserver.

That should have been fixed by #1007, although I haven't done any testing with 3PID invites.

**Comment by Kegsay** [comment]
Reopen if this becomes an issue - we don't need an issue per failing sytest.
