### ISSUE TITLE
client-api-server can race with roomserver when querying latest events & state (and constant queries are inefficient)

### ISSUE THREAD

**Issue by ara4n** [matrix-org/dendrite#81]
I was surprised that whenever I send a message on client-api-server, it first calls QueryLatestEventsAndState on the roomserver to get latest events & state.  This seems inefficient as we're having to do another HTTP hit before we even add anything to the kafka log.  It also seems to provide a race between the roomserver being queried by HTTP and the kafka entry actually getting consumed by the roomserver.

I'd expect that we might need some way to mitigate the race - e.g. putting something in the kafka log to describe the state that the client-api-sever was going on when it sent the event.

Separately, i wonder if there's scope for doing some kind of predictive optimisation on the client-api-server to avoid it having to constantly query the roomserver state all the time.

**Comment by Kegsay** [comment]
> This seems inefficient as we're having to do another HTTP hit before we even add anything to the kafka log

I agree it's sub-optimal that we need to continually ask the room server for information about the state of the room, but I don't see how else we can do this without making `client-api-server` know all about the room state (which only the `room-server` for that room knows).

> It also seems to provide a race between the roomserver being queried by HTTP and the kafka entry actually getting consumed by the roomserver.

Yes, this is possible. This would manifest itself as 2 events having the same `prev_events` and effectively forking the DAG. It's not possible to just queue these requests up in the `client-api-server` because clients may be hitting different instances of `client-api-server` and hence not know that 2 events are being sent in succession. If we force a given user ID to always use a specific `client-api-server` then we can kill the race for the common case of "send a bunch of messages all at once and expect the order to be correct".

> putting something in the kafka log to describe the state that the client-api-sever was going on when it sent the event.

This is effectively what we are already doing. The `client-api-server` uses the information returned from `QueryLatestEventsAndState` to populate `prev_events` and `auth_events`, which is then sent into the kafka log because we send the entire event into the log.

> some kind of predictive optimisation on the client-api-server to avoid it having to constantly query the roomserver state all the time

We can't AFAIK. `client-api-server` is NOT responsible for maintaining the state of the room, the `room-server` is. As a result, any kind of prediction (eg assuming that the state has remained unchanged) can result in an event being created which *doesn't pass auth checks* and is then dropped by the room server, which is arguably worse than the current scenario.

I'm open to suggestions on how this can be done better, but I think you'll be hard pressed to find a solution which works with Dendrite's loosely coupled component architecture.

**Comment by NegativeMjark** [comment]
The API for writing events to the roomserver is now a synchronous HTTP API which eliminates the race-condition as of #161. There may still be opportunities for reducing the number of round-trips when sending a message, but I don't think there needs to be a specific issue to track it.
