### ISSUE TITLE
Change repo root

### ISSUE THREAD

**Issue by Gurgy** [matrix-org/dendrite#9]
Currently the root of this repository is equal to the systems `$GOPATH`. 

I sugest you move it to the actual project folder `$GOPATH/src/github.com/matrix-org/dendrite`.

The `$GOPATH` path contains (all) Go-code on a system and moving the repository root would allow for intended usage of `go get`.

Please read this guide on the matter: [Code organization](https://golang.org/doc/code.html#Organization)

**Comment by Kegsay** [comment]
We are aware that the directory structure is atypical for Go packages. We have no plans at present to change the structure.

Dendrite uses project-based workflows rather than Go's incessant demands for workspace-based workflows, so developers are free to `git clone` this repository wherever they like. We use [gb](https://getgb.io/) as our build tool, which demands there be a `/src` directory at the top-level.
