### ISSUE TITLE
Invites over federation don't seem to work

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#909]
This could be a P2P thing though, I don't know yet.

**Comment by neilalexander** [comment]
As a sidenote here, Dendrite only implements the `v1` endpoint for invites over federation. The spec states:

> Servers should prefer to use the v2 API for invites instead of the v1 API. 

... therefore I suggest we opt for removing it and implementing the `v2` endpoint only, so that we always have the room version available at invite time (since this matters when we assign the room NID for the first time).

**Comment by neilalexander** [comment]
Fixed following #977, #979, #982, #1007.
